print('Welcome to The Winding Road')
print('Please select from the options below:')
print('1: New Game')
print('2: Saved Game')
print('3: Settings')
print('Selection:')
myInput = input()
print('You have selected ' + myInput)